POST http://localhost:3000/users/login 

Content-Type: application/json

{
  "u_name": "Tamjid",
  "_password": "hehehehe"
}
###

DELETE http://localhost:3000/users/login
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1X25hbWUiOiJUYW1qaWQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTUwMTQ5ODl9.UrjCUTyo25-6zkIqxckHThDBjdDtSU1qZgj3tsuPI2Q
Content-Type: application/json
{
    "u_name": "tamjid",
    "_password": "hehehehe"
}
###

GET  http://localhost:3000/users
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1X25hbWUiOiJUYW1qaWQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTUwMTQ5ODl9.UrjCUTyo25-6zkIqxckHThDBjdDtSU1qZgj3tsuPI2Q
###

DELETE  http://localhost:3000/users
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1X25hbWUiOiJUYW1qaWQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTUwMTQ5ODl9.UrjCUTyo25-6zkIqxckHThDBjdDtSU1qZgj3tsuPI2Q

Content-Type: application/json
{
    "u_name": "himu"
}
###



